chore: [CO-578] remove DNS/MX attributes
Zextras/carbonio-ldap-utilities pull request #35
Opened 2023-04-14 07:54 UTC by aheeva-yuliya

2023-04-14 07:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zextras/carbonio-ldap-utilities?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zextras/carbonio-ldap-utilities?pullRequest=35) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zextras/carbonio-ldap-utilities?pullRequest=35) it.</sub>

2023-04-19 10:29 UTC, keshavbhatt approved these changes

2023-04-19 10:34 UTC, frisonisland requested changes
I don't think these files are even used. I plan to remove them in a next PR: https://github.com/Zextras/carbonio-ldap-utilities/compare/devel...chore/CO-603
IMHO you can remove them.
Reason is, at build time, used attrs.xml file is the one from Mailbox, not this. Maybe verify it yourself to double-check.

2023-04-19 11:21 UTC, aheeva-yuliya commented
> I plan to remove them in a next PR: [devel...chore/CO-603](https://github.com/Zextras/carbonio-ldap-utilities/compare/devel...chore/CO-603) ok then

2023-04-19 11:22 UTC, closed without merging