feat: [CO-699] add cleanup script
Zextras/carbonio-ldap-utilities pull request #39
Opened 2023-05-08 13:01 UTC by frisonisland

2023-05-09 09:26 UTC, Polpetta requested changes
Logic seems ok, since it is new codebase I'd start to print errors into `stderr` in order to properly use linux output streams

2023-05-09 09:26 UTC, Polpetta commented on src/libexec/ldapattributecleanup
> +}
Does it make sense to put a simple error description to stderr before exiting?

2023-05-09 09:26 UTC, Polpetta commented on src/libexec/ldapattributecleanup
> +    print "Unable to bind: $!";
If this is an error message it should be logged to `stderr` instead of `stdout`

2023-05-09 10:09 UTC, frisonisland commented
> LGTM, what about the backup step? Will it be asked separately as step in upgrade notes for the upcoming release?

Yes, we decided the backup is out of scope for now, so backup is manually done.

2023-05-09 10:25 UTC, keshavbhatt approved these changes
LGTM.

2023-05-09 13:49 UTC, frisonisland commented on src/libexec/ldapattributecleanup
> +}
I added a STDERR message

2023-05-09 13:49 UTC, frisonisland commented on src/libexec/ldapattributecleanup
> +    print "Unable to bind: $!";
Added stderr

2023-05-09 13:51 UTC, frisonisland commented
@keshavbhatt @Polpetta I added a return status to apply_cleanup() and update_zimbra_ldap_schema_version() ro returns a boolean representing failure status. I think it needs further refinement to avoid leaving ldap connection open, etc.

2023-05-09 15:32 UTC, keshavbhatt approved these changes
LGTM.

2023-05-09 15:35 UTC, keshavbhatt commented on src/libexec/ldapattributecleanup
> +        print STDOUT "Found $size entries with attribute $attribute.\n";
```suggestion
        print STDOUT "Found $size entries with attribute $attribute\n";
```
I was testing this and found that `.` after attributes names ugly

```Executing cleanup from 1681988810.json
Found 0 entries with attribute dcarbonioAdminPort.
Found 0 entries with attribute dcarbonioAdminPortTwo.
Found 0 entries with attribute dcarbonioAdminPortThree.
```

2023-05-09 15:42 UTC, frisonisland commented on src/libexec/ldapattributecleanup
> +        print STDOUT "Found $size entries with attribute $attribute.\n";
Thx, I was checking what was wrong with these attribute names at first :laughing:

2023-05-10 07:35 UTC, Polpetta approved these changes

2023-05-10 07:41 UTC, merged